CREATE DATABASE IF NOT EXISTS devblog;
USE devblog;

CREATE TABLE IF NOT EXISTS posts (
    id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    views INT DEFAULT 0
);